### ISSUE TITLE
Publish an all-in-one docker image?

### ISSUE THREAD

**Issue by nfriedly** [marcobaobao/yt-dlp-web-ui#1]
Hey, this is awesome, thanks for making it! Is there any chance you could put together an all-in-one image that includes this frontend + the yt-dlp binary and publish it to docker hub?

**Comment by marcobaobao** [comment]
Hi! I've published the image on docker hub and it's entirely automated as you suggested. You'll find everything in the updated Readme.md.

**Comment by nfriedly** [comment]
Thanks, you're the best!
