### ISSUE TITLE
cannot stop main.js gracefully?

### ISSUE THREAD

**Issue by deluxghost** [marcobaobao/yt-dlp-web-ui#3]
I'm using docker deployment, the `docker stop` takes longer than 10 seconds to be done

I think `node dist/main.js` ignores SIGTERM, so docker must wait until the default 10s timeout and kill the container

**Comment by marcobaobao** [comment]
It shouldn't be too much trouble ti fix. Forcing a custom handler with e.g 

process.once('SIGTERM' , () => _stop routine_)

When I'll have some spare time I'll try to fix it.

**Comment by marcobaobao** [comment]
> I'm using docker deployment, the `docker stop` takes longer than 10 seconds to be done
> 
> I think `node dist/main.js` ignores SIGTERM, so docker must wait until the default 10s timeout and kill the container

I pushed a possible fix. Now docker stops the container immediately as suggested.
